# Numpy Introduction

Numpy provides a memory efficient method for storing large amounts of different values. The values are stored in a matrix format, meaning the index of the value is the only method of identifying them

In [5]:
#Exercise 1
# Please identify what version of numpy is installed 
print("Expected Output: \n1.18.1")

Expected Output: 
1.18.1


In [ ]:
#Solution


In [33]:
#Exercise 2
#Create a numpy array containing all odd numbers between 1 and 10, print it
#Note: store the array for later use
print("Expected Output:\n[1 3 5 7 9]")

Expected Output:
[1 3 5 7 9]


In [17]:
#Solution
import numpy as np
array = np.array([1,3,5,7,9])
print(array)

[1 3 5 7 9]


In [40]:
#Exercise 2
#Add all of the even values between 1-10 to the array from Exercise 2
print("Expected Output:\n[ 1  3  5  7  9  2  4  6  8 10]")

Expected Output:
[ 1  3  5  7  9  2  4  6  8 10]


In [38]:
#Solution
n=2
while n<11:
    array=np.append(array,np.array(n))
    n=n+2
print(array)

2
4
6
8
10
[ 1  3  5  7  9  2  4  6  8 10]


In [55]:
#Hint: You can create an array contain set of values using arange()
arr= np.arange(0,50)
#You can print a certain value by entering the index, you can use positve indexs and negative indexes
print(arr[39])
print("The last value can be referred to as index -1: " + str(arr[-1]))
print("The last value can also be referred to as index 49: " + str(arr[49]))
print("The second to last value can be referred to as index -2: " + str(arr[-2]))
print("The last value can also be referred to as index 48: " + str(arr[48]))

39
The last value can be referred to as index -1: 49
The last value can also be referred to as index 49: 49
The second to last value can be referred to as index -2: 48
The last value can also be referred to as index 48: 48


In [45]:
#Exercise 3
#Create an array with values from 1-10 in ascending order
print("Expected Output:\n[ 1  2  3  4  5  6  7  8  9 10]")

Expected Output:
[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
#Solution
print(np.arange(1,11,1))

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
#Exercise 4
#Remove all odd values from array used in previous solution
#You can filter values out using the index reference
print("Expected Output:\n[2  4  6  8 10]")

Expected Output:
[2  4  6  8 10]


In [51]:
#Solution
array=array[array%2==0]
print(array)

[ 2  4  6  8 10]


In [64]:
#Exercise 5 
#Lets apply statisical analysis to numpy values!
#print the average value and the standard deviation of an array of random interger values(20 Values)
#between (0,20)
#import numpy.random as rand
#hint: np.random_int() creates an array of psuedorandom values
print("Expected Output:\n[A R R A Y O F 2 0 V A L U E S]\n Mean: x.xx\n Std: x.xx")

Expected Output:
[A R R A Y O F 2 0 V A L U E S]
 Mean: x.xx
 Std: x.xx


In [72]:
#Solution
import numpy.random as rand
array= rand.randint(0,20,20)
print(array)
mean = np.average(array)
std = np.std(array)
print("Mean: %.2f"%mean)
print("Std: %.2f"%std)

[ 1 15 14 16 17 11 16  7 15 13  5  8 19 10  3 11 13 13 14  5]
Mean: 11.30
Std: 4.86


In [ ]:
#Now a larger exercise(You can choose to complete this yourself or 
#set up a time with Zach to go through it together):
#you are give a thousand students grades from the last calculus 1 exam:
#Part 1: Use matplotlib to create a histogram
# Label histogram with title, x&y labels, include major gridlines.
# Change The color scheme to something prettier(As long as it's not the default)
# Extension: Create distplot using seaborn
#Part 2: 